sudo: required
language: node_js
node_js:
  - "6"
services:
  - docker
env:
  global:
    - QUAY_REPO="quay.io/opentargets/webapp"
cache: yarn
before_install:
#  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
#  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
#  - sudo apt-get update -qq
#  - sudo apt-get install -y -qq yarn
# https://gist.github.com/topheman/25241e48a1b4f91ec6d4
  - yarn add jspm@^0.16.34
  - jspm config registries.github.remote https://github.jspm.io
  - jspm config registries.github.strictSSL false
  - jspm config registries.github.auth "${JSPM_GITHUB_AUTH_TOKEN}"
  - jspm config registries.github.maxRepoSize 500
  - jspm config registries.github.handler jspm-github
  - jspm config strictSSL false
install:
  - yarn install
  - yarn run setup
script:
  - yarn run eslint
  - yarn run test
notifications:
  email:
    recipients:
      - ops@opentargets.org
    on_success: never
    on_failure: always
after_success:
#  - ./node_modules/.bin/codecov -e ${TRAVIS_NODE_VERSION} -f ./coverage/lcov.info
  - docker pull "${QUAY_REPO}:${TRAVIS_BRANCH}" || true
  - docker build --pull --cache-from "${QUAY_REPO}:${TRAVIS_BRANCH}" --tag "${QUAY_REPO}" .
  - docker login -u="${QUAY_USER}" -p="${QUAY_PASSWORD}" quay.io
  - git_sha="${TRAVIS_COMMIT}"
  - docker tag "${QUAY_REPO}" "${QUAY_REPO}:${TRAVIS_BRANCH}"
  - docker tag "${QUAY_REPO}" "${QUAY_REPO}:${git_sha}-${TRAVIS_BRANCH}"
  - docker push "${QUAY_REPO}:${TRAVIS_BRANCH}" && docker push "${QUAY_REPO}:${git_sha}-${TRAVIS_BRANCH}"
  - |
    if [ "${TRAVIS_BRANCH}" = "master" ]; then
      docker tag "${QUAY_REPO}:${TRAVIS_BRANCH}" "${QUAY_REPO}:latest"
      docker push "${QUAY_REPO}:latest"
    fi
