# Global settings applied to the whole site.
[build]
  base    = "/"
  publish = "app/"
  command = "yarn run setup"

# Read https://www.netlify.com/docs/continuous-deployment/#deploy-contexts
# to understand how context below works.

# Master branch
[context.production.environment]
  APIHOST = "https://api.opentargets.io/"

# Deploy Preview context: All Deploy Previews (ie.PRs)
# will inherit these settings.
[context.deploy-preview.environment]
  APIHOST = "https://api.opentargets.io/"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy.environment]
  APIHOST = "https://api.opentargets.io/"

# CAREFUL!!! When you point a particular branch to a specific API below,
# the change will not continue working once the branch is merged into master.
[context.feature.environment]
  APIHOST = "https://api.opentargets.io/"

[context.master.environment]
  APIHOST = "https://open-targets-eu-dev.appspot.com/"

[context.mouse-phenotypes.environment]
  APIHOST = "https://yapsy-dot-open-targets-eu-dev.appspot.com/"

[context.mk-batchsearch.environment]
  APIHOST = "https://mk-batchsearch-dot-open-targets-eu-dev.appspot.com/"

[context.biomarkers.environment]
  # APIHOST = "https://staging-api.opentargets.io/"
  APIHOST = "https://open-targets-eu-dev.appspot.com/"

[context.v3.6.environment]
  APIHOST = "https://open-targets-eu-dev.appspot.com/"